package me.liuweiqiang.idempotent.dao.model;

public class NewTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotent..new_table.id
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotent..new_table.for_test
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    private String forTest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotent..new_table.id
     *
     * @return the value of idempotent..new_table.id
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotent..new_table.id
     *
     * @param id the value for idempotent..new_table.id
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotent..new_table.for_test
     *
     * @return the value of idempotent..new_table.for_test
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    public String getForTest() {
        return forTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotent..new_table.for_test
     *
     * @param forTest the value for idempotent..new_table.for_test
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    public void setForTest(String forTest) {
        this.forTest = forTest;
    }
}