package me.liuweiqiang.idempotent.dao.model;

public class Request {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotent..request.id
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotent..request.consumer
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    private String consumer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotent..request.request_id
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    private String requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotent..request.status
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotent..request.id
     *
     * @return the value of idempotent..request.id
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotent..request.id
     *
     * @param id the value for idempotent..request.id
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotent..request.consumer
     *
     * @return the value of idempotent..request.consumer
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    public String getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotent..request.consumer
     *
     * @param consumer the value for idempotent..request.consumer
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    public void setConsumer(String consumer) {
        this.consumer = consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotent..request.request_id
     *
     * @return the value of idempotent..request.request_id
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotent..request.request_id
     *
     * @param requestId the value for idempotent..request.request_id
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotent..request.status
     *
     * @return the value of idempotent..request.status
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotent..request.status
     *
     * @param status the value for idempotent..request.status
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }
}