package me.liuweiqiang.idempotent.dao;

import java.util.List;
import me.liuweiqiang.idempotent.dao.model.NewTable;
import me.liuweiqiang.idempotent.dao.model.NewTableExample;
import org.apache.ibatis.annotations.Param;

public interface NewTableDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    long countByExample(NewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    int deleteByExample(NewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    int insert(NewTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    int insertSelective(NewTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    List<NewTable> selectByExample(NewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    NewTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") NewTable record, @Param("example") NewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    int updateByExample(@Param("record") NewTable record, @Param("example") NewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    int updateByPrimaryKeySelective(NewTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..new_table
     *
     * @mbg.generated Wed Dec 15 21:48:17 CST 2021
     */
    int updateByPrimaryKey(NewTable record);
}