package me.liuweiqiang.idempotent.dao;

import java.util.List;
import me.liuweiqiang.idempotent.dao.model.Request;
import me.liuweiqiang.idempotent.dao.model.RequestExample;
import org.apache.ibatis.annotations.Param;

public interface RequestDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    long countByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    int deleteByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    int insert(Request record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    int insertSelective(Request record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    List<Request> selectByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    Request selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    int updateByExampleSelective(@Param("record") Request record, @Param("example") RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    int updateByExample(@Param("record") Request record, @Param("example") RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    int updateByPrimaryKeySelective(Request record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotent..request
     *
     * @mbg.generated Sat Dec 11 14:48:05 CST 2021
     */
    int updateByPrimaryKey(Request record);
}